#!/usr/bin/env python3
"""
Generate main/secrets.h from repo-root secret files.

  .wifi    line 1 = SSID, line 2 = password
  .apikey  single line; generated automatically if missing

Both are gitignored, as is the header this produces. Only lengths are printed,
never the values, so it is safe to run in a shared terminal.

    python tools/gen_secrets.py
"""

import os
import secrets
import stat
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, os.pardir))
WIFI = os.path.join(ROOT, ".wifi")
APIKEY = os.path.join(ROOT, ".apikey")
OUT = os.path.join(ROOT, "main", "secrets.h")

TEMPLATE = """\
/*
 * GENERATED by tools/gen_secrets.py - DO NOT COMMIT.
 * Regenerate with: python tools/gen_secrets.py
 */

#pragma once

#define WIFI_SSID "{ssid}"
#define WIFI_PASS "{password}"
#define API_KEY "{apikey}"
"""


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def load_or_create_apikey():
    if os.path.exists(APIKEY):
        with open(APIKEY, encoding="utf-8") as fh:
            key = fh.read().strip()
        if key:
            return key, False
    key = secrets.token_urlsafe(32)
    with open(APIKEY, "w", newline="\n", encoding="utf-8") as fh:
        fh.write(key + "\n")
    try:
        os.chmod(APIKEY, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass
    return key, True


def main():
    if not os.path.exists(WIFI):
        sys.exit(f"no .wifi file at {WIFI}\n"
                 f"create it with your SSID on line 1 and password on line 2")

    with open(WIFI, encoding="utf-8") as fh:
        lines = [ln.strip() for ln in fh.read().splitlines() if ln.strip()]
    if len(lines) < 2:
        sys.exit(".wifi must have SSID on line 1 and password on line 2")
    ssid, password = lines[0], lines[1]

    apikey, created = load_or_create_apikey()

    with open(OUT, "w", newline="\n", encoding="utf-8") as fh:
        fh.write(TEMPLATE.format(ssid=c_escape(ssid),
                                 password=c_escape(password),
                                 apikey=c_escape(apikey)))

    print(f"wrote {OUT}")
    print(f"  SSID: {len(ssid)} chars, password: {len(password)} chars")
    print(f"  API key: {'GENERATED' if created else 'loaded'}, {len(apikey)} chars"
          f" (in {APIKEY}, gitignored)")


if __name__ == "__main__":
    main()
